add html
WebSergeevDima/purpleschool-homework-html-css pull request #1
Opened 2023-10-29 17:29 UTC by WebSergeevDima

add html for Blog-1

2023-11-28 10:13 UTC, Levitinn requested changes

2023-11-28 10:13 UTC, Levitinn commented on Blog-1/index.html
> +    <input type="search" value="Поиск" class="search"/>
инпут стоит оборачивать в див либо label

2023-11-28 10:13 UTC, Levitinn commented on Blog-1/index.html
> +
лишние пробелы

2023-11-28 10:13 UTC, Levitinn commented on Blog-1/index.html
> +
дальше по разметке они тоже встречаются. нужно убрать

2023-11-28 10:13 UTC, Levitinn commented on Blog-1/index.html
> +                <img src="./images/avatar.png" alt="Аватарка автора статьи">
img всегда стоит оборачивать в отдельный див, и управлять размерами картинки через стили к этому диву. а img задать width: 100% height: 100%

2023-11-28 10:13 UTC, Levitinn commented on Blog-1/index.html
> +                <img src="./images/avatar.png" alt="Аватарка автора статьи">
ниже картинки так же стоит обернуть в дивы

2023-11-28 15:39 UTC, WebSergeevDima commented
Исправил

2023-12-07 17:54 UTC, Levitinn approved these changes

2024-02-14 22:40 UTC, merged