Feature/2 miro
WebSergeevDima/purpleschool-homework-html-css pull request #4
Opened 2023-11-27 20:11 UTC by WebSergeevDima

2023-11-28 10:18 UTC, Levitinn requested changes

2023-11-28 10:18 UTC, Levitinn commented on 2-Miro/index.html
> +            <button class="form__button">Начать бесплатно</button>
type="submit"

2023-11-28 10:18 UTC, Levitinn commented on 2-Miro/index.html
> +            <input type="email" class="form__email">
обернуть в див нужно

2023-11-28 10:18 UTC, Levitinn commented on 2-Miro/index.html
> +        <img src="./images/01.png" alt="Сервисы Miro">
обернуть в див. как и сказал ранее

2023-11-28 10:18 UTC, Levitinn commented on 2-Miro/style/style.css
> +    font-size: 18px;
дублируется стиль font-size можно вынести повторяющиеся стили в отдельные классы, например, чтобы не повторяться

2023-11-28 15:39 UTC, WebSergeevDima commented
Исправил недочёты

2023-12-07 17:56 UTC, Levitinn approved these changes

2023-12-07 17:56 UTC, Levitinn commented on 2-Miro/style/style.css
> +nav {
пустой стиль

2024-02-14 22:40 UTC, merged